#!/bin/sh
set -e

if [ -n "$FLY_TARGET" ]
then
    FLY_TARGET=main
fi

config=pipeline.yml
while getopts c: name
do
    case $name in
    p)    config="$OPTARG";;
    ?)    printf "usage: %s: [-c config]\n" $0
          exit 2;;
    esac
done
shift $(($OPTIND - 1))
unset name

# if [ ! -f "${HOME}/.flyrc" ]
# then
#     printf "%s: can't open .flyrc: No such file or directory.\n" $0
#     exit
# fi

pipeline="$(git rev-parse --show-toplevel)"
fly -t "$FLY_TARGET" set-pipeline \
    --pipeline "$pipeline" \
    --config "$config"
